name: Test Merge from Develop

on:
  workflow_dispatch:
    inputs:
      action-ref:
        type: string
        required: true

jobs:

  merge-from-develop:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4
      with:
        fetch-depth: 0                  # the full GIT history needs to be checked out

    - name: Merge from Develop to PR (develop)
      if: inputs.action-ref == 'develop'
      uses: maven-flow/merge@develop
      with:
        changelog-rebase: true
        push-changes: false
        source-branch: origin/develop
        target-branch: ${{ github.ref_name }}

    - name: Merge from Develop to PR (main)
      if: inputs.action-ref == 'main'
      uses: maven-flow/merge@main
      with:
        changelog-rebase: true
        push-changes: false
        source-branch: origin/develop
        target-branch: ${{ github.ref_name }}

    - name: Merge from Develop to PR (v1)
      if: inputs.action-ref == 'v1'
      uses: maven-flow/merge@v1
      with:
        changelog-rebase: true
        push-changes: false
        source-branch: origin/develop
        target-branch: ${{ github.ref_name }}

    - name: Check pom.xml
      run: |
        echo "----------------"
        cat pom.xml
        echo "----------------"
        diff pom.xml expected-files/from-develop-to-feature/pom.xml

    - name: Check CHANGELOG.md
      if: always()                      # do this check even if previous check fails
      run: |
        echo "----------------"
        cat CHANGELOG.md
        echo "----------------"
        diff CHANGELOG.md expected-files/from-develop-to-feature/CHANGELOG.md
